import { Claim } from '@/lib/types';

export const MOCK_CLAIMS: Record<string, Claim> = {
  '1': {
    id: '1',
    input_type: 'url',
    input_content: 'https://example.com/article1',
    extracted_claim: 'Scientists have discovered a new species of butterfly in the Amazon rainforest.',
    category: 'Science',
    track_context: 'consumer',
    status: 'completed',
    agent_progress: 'Verification completed',
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-01-15T14:20:00Z',
    verification: {
      id: 'v1',
      claim_id: '1',
      badge: 'blue',
      confidence_score: 0.94,
      verdict_summary: 'Verified: Multiple independent sources confirm the discovery.',
      detailed_analysis: 'Three scientific journals and two official biodiversity databases confirm the existence of this new species.\n\n- Journal of Entomology, Vol. 45, pp. 123-145\n- Amazon Biodiversity Institute Report\n- Global Butterfly Database\n- National Geographic Verification\n- BBC Nature Documentary Footage',
      primary_sources_count: 2,
      secondary_sources_count: 3,
      contradictions_found: 0,
      fact_checks_found: 2,
      processing_time_ms: 1250,
      model_used: 'google/gemma-4-31b-it',
      created_at: '2024-01-15T14:20:00Z',
      sources: [
        {
          id: 's1',
          verification_id: 'v1',
          url: 'https://example.com/source1',
          title: 'Discovery of new butterfly species in Amazon',
          domain: 'journalofentomology.com',
          source_type: 'academic',
          credibility_tier: 'high',
          publication_date: '2024-01-10',
          author: 'Dr. Maria Silva',
          extracted_snippet: 'We describe a new species of Lepidoptera found in the northwestern Amazon basin.',
          relevance_score: 0.95,
          bright_data_tool_used: 'ACADEMIC_SCRAPER',
        },
        {
          id: 's2',
          verification_id: 'v1',
          url: 'https://example.com/source2',
          title: 'Amazon Biodiversity Survey 2024',
          domain: 'amazonbiodiversity.org',
          source_type: 'official',
          credibility_tier: 'high',
          publication_date: '2024-01-12',
          author: 'Amazon Biodiversity Institute',
          extracted_snippet: 'The survey identified 12 new insect species, including a previously undocumented butterfly.',
          relevance_score: 0.90,
          bright_data_tool_used: 'OFFICIAL_DATA_FEED',
        }
      ],
    },
  },
  '2': {
    id: '2',
    input_type: 'text',
    input_content: 'The new government policy will reduce taxes for all citizens by 20%.',
    extracted_claim: 'The new government policy will reduce taxes for all citizens by 20%.',
    category: 'Politics',
    track_context: 'consumer',
    status: 'completed',
    agent_progress: 'Verification completed',
    created_at: '2024-01-14T09:15:00Z',
    updated_at: '2024-01-14T16:45:00Z',
    verification: {
      id: 'v2',
      claim_id: '2',
      badge: 'green',
      confidence_score: 0.87,
      verdict_summary: 'Confirmed: Official government document directly confirms the policy details.',
      detailed_analysis: 'The official gazette published by the Ministry of Finance confirms the tax reduction policy.',
      primary_sources_count: 1,
      secondary_sources_count: 2,
      contradictions_found: 0,
      fact_checks_found: 1,
      processing_time_ms: 980,
      model_used: 'google/gemma-4-31b-it',
      created_at: '2024-01-14T16:45:00Z',
      sources: [
        {
          id: 's3',
          verification_id: 'v2',
          url: 'https://example.com/source3',
          title: 'Official Gazette: Tax Policy Update',
          domain: 'governmentgazette.gov',
          source_type: 'official',
          credibility_tier: 'high',
          publication_date: '2024-01-10',
          author: 'Ministry of Finance',
          extracted_snippet: 'Effective Q2 2024, personal income tax rates will be reduced by 20% for all brackets.',
          relevance_score: 0.98,
          bright_data_tool_used: 'OFFICIAL_DATA_FEED',
        }
      ],
    },
  },
  '3': {
    id: '3',
    input_type: 'topic',
    input_content: 'AI regulation',
    extracted_claim: 'Recent studies show that AI regulation will stifle innovation in the tech sector.',
    category: 'Technology',
    track_context: 'track1_gtm',
    status: 'completed',
    agent_progress: 'Verification completed',
    created_at: '2024-01-13T11:00:00Z',
    updated_at: '2024-01-13T15:30:00Z',
    verification: {
      id: 'v3',
      claim_id: '3',
      badge: 'yellow',
      confidence_score: 0.65,
      verdict_summary: 'Partially True: While some regulations may impact certain aspects, overall innovation continues.',
      detailed_analysis: 'Academic research shows mixed effects - some compliance costs exist but innovation adapts and continues.',
      primary_sources_count: 1,
      secondary_sources_count: 4,
      contradictions_found: 1,
      fact_checks_found: 3,
      processing_time_ms: 2100,
      model_used: 'google/gemma-4-31b-it',
      created_at: '2024-01-13T15:30:00Z',
      sources: [
        {
          id: 's4',
          verification_id: 'v3',
          url: 'https://example.com/source4',
          title: 'Impact of AI Regulation on Innovation',
          domain: 'stanford.edu',
          source_type: 'academic',
          credibility_tier: 'high',
          publication_date: '2023-11-15',
          author: 'Prof. James Chen',
          extracted_snippet: 'While reporting requirements increased development costs by 8%, patent filings continued to grow at 12% annually.',
          relevance_score: 0.88,
          bright_data_tool_used: 'ACADEMIC_SCRAPER',
        }
      ],
    },
  },
  '4': {
    id: '4',
    input_type: 'url',
    input_content: 'https://example.com/article4',
    extracted_claim: 'A celebrity endorsed a new cryptocurrency that guaranteed 100% returns.',
    category: 'Entertainment',
    track_context: 'consumer',
    status: 'completed',
    agent_progress: 'Verification completed',
    created_at: '2024-01-12T14:20:00Z',
    updated_at: '2024-01-12T18:10:00Z',
    verification: {
      id: 'v4',
      claim_id: '4',
      badge: 'orange',
      confidence_score: 0.72,
      verdict_summary: 'Misleading: The celebrity did mention the crypto but did not guarantee returns.',
      detailed_analysis: 'The celebrity\'s actual statement was about the technology\'s potential, not a financial guarantee.',
      primary_sources_count: 1,
      secondary_sources_count: 3,
      contradictions_found: 2,
      fact_checks_found: 4,
      processing_time_ms: 1750,
      model_used: 'google/gemma-4-31b-it',
      created_at: '2024-01-12T18:10:00Z',
      sources: [
        {
          id: 's5',
          verification_id: 'v4',
          url: 'https://example.com/source5',
          title: 'Celebrity Denies Guarantee Claims',
          domain: 'entertainmentnews.com',
          source_type: 'news',
          credibility_tier: 'medium',
          publication_date: '2024-01-11',
          author: 'Sarah Johnson',
          extracted_snippet: 'When asked about returns, the celebrity stated they were discussing blockchain technology potential.',
          relevance_score: 0.92,
          bright_data_tool_used: 'NEWS_SCRAPER',
        }
      ],
    },
  },
  '5': {
    id: '5',
    input_type: 'text',
    input_content: 'The moon landing was faked in a Hollywood studio.',
    extracted_claim: 'The moon landing was faked in a Hollywood studio.',
    category: 'Conspiracy',
    track_context: 'consumer',
    status: 'completed',
    agent_progress: 'Verification completed',
    created_at: '2024-01-11T08:45:00Z',
    updated_at: '2024-01-11T12:00:00Z',
    verification: {
      id: 'v5',
      claim_id: '5',
      badge: 'red',
      confidence_score: 0.96,
      verdict_summary: 'False: Directly contradicted by multiple independent sources including moon rock samples.',
      detailed_analysis: 'NASA telemetry, third-party tracking data, and lunar samples all confirm the authenticity of the moon landings.',
      primary_sources_count: 3,
      secondary_sources_count: 5,
      contradictions_found: 5,
      fact_checks_found: 6,
      processing_time_ms: 1100,
      model_used: 'google/gemma-4-31b-it',
      created_at: '2024-01-11T12:00:00Z',
      sources: [
        {
          id: 's6',
          verification_id: 'v5',
          url: 'https://example.com/source6',
          title: 'Analysis of Moon Rocks Confirms Lunar Origin',
          domain: 'nasa.gov',
          source_type: 'official',
          credibility_tier: 'high',
          publication_date: '2024-01-05',
          author: 'NASA Lunar Sample Laboratory',
          extracted_snippet: 'Isotopic analysis confirms the lunar samples have characteristics unique to moon formation.',
          relevance_score: 0.99,
          bright_data_tool_used: 'OFFICIAL_DATA_FEED',
        }
      ],
    },
  },
  '6': {
    id: '6',
    input_type: 'topic',
    input_content: 'Ancient alien civilizations',
    extracted_claim: 'There is insufficient evidence to confirm or deny the existence of ancient alien civilizations visiting Earth.',
    category: 'History',
    track_context: 'consumer',
    status: 'completed',
    agent_progress: 'Verification completed',
    created_at: '2024-01-10T16:30:00Z',
    updated_at: '2024-01-10T16:35:00Z',
    verification: {
      id: 'v6',
      claim_id: '6',
      badge: 'gray',
      confidence_score: 0.30,
      verdict_summary: 'Unverifiable: Insufficient public data to render a verdict on this topic.',
      detailed_analysis: 'While there are intriguing artifacts, no credible scientific evidence supports or refutes the claim.',
      primary_sources_count: 0,
      secondary_sources_count: 2,
      contradictions_found: 0,
      fact_checks_found: 0,
      processing_time_ms: 800,
      model_used: 'google/gemma-4-31b-it',
      created_at: '2024-01-10T16:35:00Z',
      sources: [
        {
          id: 's7',
          verification_id: 'v6',
          url: 'https://example.com/source7',
          title: 'Evaluation of Ancient Artifact Claims',
          domain: 'archaeologyjournal.com',
          source_type: 'academic',
          credibility_tier: 'medium',
          publication_date: '2023-12-20',
          author: 'Dr. Elena Rodriguez',
          extracted_snippet: 'While artifacts show advanced craftsmanship, no evidence indicates extraterrestrial origin or assistance.',
          relevance_score: 0.75,
          bright_data_tool_used: 'ACADEMIC_SCRAPER',
        }
      ],
    },
  },
};
