import jsPDF from 'jspdf'
import type { Verification, Claim, Source } from './types'
import { BADGE_CONFIG } from './types'

export async function generateBattlecard(claim: Claim, verification: Verification, sources: Source[]) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = 210; const margin = 20; const contentW = W - margin * 2

  // Header
  doc.setFillColor(10, 15, 13)
  doc.rect(0, 0, W, 40, 'F')
  doc.setTextColor(240, 253, 244)
  doc.setFontSize(20)
  doc.text('Verified News', margin, 20)
  doc.setFontSize(10)
  doc.setTextColor(107, 114, 128)
  doc.text('Competitive Intelligence Battlecard', margin, 28)
  doc.text(new Date().toLocaleDateString(), W - margin, 28, { align: 'right' })

  // Badge
  const badge = BADGE_CONFIG[verification.badge]
  const [r, g, b] = hexToRgb(badge.hex)
  doc.setFillColor(r, g, b)
  doc.roundedRect(margin, 48, 60, 20, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(12)
  doc.text(`${badge.label}  ${(verification.confidence_score * 100).toFixed(0)}%`, margin + 30, 61, { align: 'center' })

  // Claim
  doc.setTextColor(10, 15, 13)
  doc.setFontSize(11)
  doc.text('Claim Under Investigation', margin, 80)
  doc.setFontSize(10)
  doc.setTextColor(50, 50, 50)
  const claimLines = doc.splitTextToSize(claim.input_content, contentW)
  doc.text(claimLines, margin, 88)
  let y = 88 + claimLines.length * 6

  // Verdict
  y += 8
  doc.setFontSize(11)
  doc.setTextColor(10, 15, 13)
  doc.text('Verdict', margin, y)
  y += 6
  doc.setFontSize(10)
  doc.setTextColor(50, 50, 50)
  const verdictLines = doc.splitTextToSize(verification.verdict_summary, contentW)
  doc.text(verdictLines, margin, y)
  y += verdictLines.length * 6

  // Stats
  y += 8
  doc.setFontSize(9)
  doc.setTextColor(107, 114, 128)
  doc.text(`Sources: ${verification.primary_sources_count + verification.secondary_sources_count}  ·  Contradictions: ${verification.contradictions_found}  ·  Fact-checks: ${verification.fact_checks_found}`, margin, y)

  // Top sources
  y += 10
  doc.setFontSize(11)
  doc.setTextColor(10, 15, 13)
  doc.text('Key Sources', margin, y)
  y += 6
  const topSources = sources.slice(0, 5)
  for (const src of topSources) {
    if (y > 260) break
    doc.setFontSize(9)
    doc.setTextColor(50, 50, 50)
    doc.text(`· [${src.credibility_tier.toUpperCase()}] ${src.domain}: ${src.title?.slice(0, 70) ?? ''}`, margin + 2, y)
    y += 6
  }

  // Counter-argument for red badges
  if (verification.badge === 'red') {
    y += 8
    doc.setFillColor(239, 68, 68, 0.1)
    doc.setFontSize(10)
    doc.setTextColor(10, 15, 13)
    doc.text('Counter-Argument for Sales', margin, y)
    y += 6
    doc.setFontSize(9)
    doc.setTextColor(50, 50, 50)
    const counterLines = doc.splitTextToSize(verification.detailed_analysis.slice(0, 300), contentW)
    doc.text(counterLines, margin, y)
  }

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(107, 114, 128)
  doc.text(`Generated by Verified News · Powered by Bright Data · Model: ${verification.model_used}`, margin, 285)

  doc.save(`battlecard-${claim.id.slice(0, 8)}.pdf`)
}

function hexToRgb(hex: string): [number, number, number] {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [0, 0, 0]
}
